// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Castle } from "./tables/Castle.sol";
import { Counter } from "./tables/Counter.sol";
import { CurrentGame } from "./tables/CurrentGame.sol";
import { EntityAtPosition } from "./tables/EntityAtPosition.sol";
import { Game, GameData } from "./tables/Game.sol";
import { Health } from "./tables/Health.sol";
import { LogicSystemAddress } from "./tables/LogicSystemAddress.sol";
import { MapConfig } from "./tables/MapConfig.sol";
import { Owner } from "./tables/Owner.sol";
import { Position } from "./tables/Position.sol";
import { Projectile } from "./tables/Projectile.sol";
import { Tower } from "./tables/Tower.sol";
